#!/usr/bin/env python

from pykfs.script import Script
import subprocess

class Grebase(Script):
    """
    Searches for a pattern in all child files
    """

    args = [
        {
            "name": "pattern", "type": str, "action": "store", "metavar": "PATTERN",
            "help": "The pattern to search for",
        },
        {
            "option_strings": ["-d", "--dryrun"], "name": "dryrun", "const": True,
            "action": "store_const", "default": False,
            "help": "Print the command to be run, but do not execute."
        }
    ]

    def do_script(self):
        command = "grep -n -H -r '{}' *".format(self.pattern)
        if self.dryrun:
            print "Command to be run:"
            print "    {}".format(command)
        else:
            grep = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
            subprocess.check_call("less", stdin=grep.stdout, shell=True)


if __name__ == "__main__":
    Grebase.execute()
